Database:
  # Tested with Postgresql 17
  PSQL:
    Host: "psql.example.com"
    Port: 5432
    User: "showmaster"
    Password: "password"
    DBName: "showmaster_db"
    Timezone: "Europe/Berlin"
  # Tested with redis-8
  Redis:
    Host: "redis.example.com"
    Port: 6379
    User: "showmaster"
    Password: "password"
    DB: 0
