services:
  web:
    image: "ghcr.io/eliasb-nu/rcjv-app:${GIT_COMMIT_HASH:-latest}"
    environment:
      - "PSQL_HOST=${PSQL_HOST}"
      - "PSQL_PORT=${PSQL_PORT}"
      - "PSQL_USER=${PSQL_USER}"
      - "PSQL_PASSWORD=${PSQL_PASSWORD}"
      - "PSQL_DBNAME=${PSQL_DBNAME}"
      - "PSQL_TIMEZONE=${PSQL_TIMEZONE}"
      - "VALKEY_HOST=${VALKEY_HOST}"
      - "VALKEY_PORT=${VALKEY_PORt}"
      - "VALKEY_DB=${VALKEY_DB}"
      - "VALKEY_USER=${VALKEY_USER}"
      - "VALKEY_PASSWORD=${VALKEY_PASSWORD}"
    networks:
      - traefik-nw
    restart: always

    deploy:
      placement:
        constraints: [node.role == worker]
      replicas: 2
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.web.loadbalancer.server.port=3006"
        - "traefik.http.routers.technulgy-website.rule=Host(`rcjv.braunelias.com`)"
        - "traefik.http.routers.technulgy-website.entrypoints=websecure"
        - "traefik.http.routers.technulgy-website.tls=true"
        - "traefik.http.routers.technulgy-website.tls.certresolver=cfACME"
        - "traefik.http.routers.technulgy-website.middlewares=redirect-to-https"

networks:
  traefik-nw:
    external: true
